#!/usr/bin/env perl

@lines = (
  "DEBUG - 2011-01-01 00:01:01 --> Model Class Initialized",
  "DEBUG - 2011-01-01 00:01:01 --> Model Class Initialized",
  "DEBUG - 2011-01-01 00:01:01 --> Database Driver Class Initialized",
  "DEBUG - 2011-01-01 00:01:01 --> Database Driver Class Initialized",
  "DEBUG - 2011-01-01 00:01:01 --> Session Class Initialized",
  "DEBUG - 2011-01-01 00:01:01 --> Session Class Initialized",
  "DEBUG - 2011-01-01 00:01:01 --> Encrypt Class Initialized",
  "DEBUG - 2011-01-01 00:01:01 --> Encrypt Class Initialized",
  "DEBUG - 2011-01-01 00:01:01 --> Session routines successfully run",
  "DEBUG - 2011-01-01 00:01:01 --> Session routines successfully run",
  "DEBUG - 2011-01-01 00:01:01 --> Controller Class Initialized",
  "DEBUG - 2011-01-01 00:01:01 --> Controller Class Initialized",
  "INFO  - 2011-01-01 00:01:01 --> Total execution time: 0.0404",
  "INFO  - 2011-01-01 00:01:01 --> New User: meowcats",
  "INFO  - 2011-01-01 00:01:01 --> Database cleanup, execution time: 1.05s",
  "INFO  - 2011-01-01 00:01:01 --> New upload, Disk 11% usage",
  "WARN  - 2011-01-01 00:01:01 --> Access denied to admin section",
  "WARN  - 2011-01-01 00:01:01 --> Access denied to admin section",
  "WARN  - 2011-01-01 00:01:01 --> Access denied to admin section",
  "ERROR - 2011-01-01 00:01:01 --> Could not connect to Redis!",
  "ERROR - 2011-01-01 00:01:01 --> Could not upload file to s3!",
	"FATAL - 2011-01-01 00:00:01 --> Could not connect to database!",
	"DEMO  - 2011-01-01 00:00:01 --> The database has no tables lol",
);


open handle, '>', 'log.txt';

for(;;) {
  select((select(handle), $|=1)[0]);
  print $lines[rand @lines] . "\n";
  print handle $lines[rand @lines] . "\n";
	sleep 1;
}
