#!/usr/bin/env perl

@lines = (
  "DEBUG - 2011-01-01 00:01:01 --> Model Class Initialized",
  "DEBUG - 2011-01-01 00:01:01 --> Model Class Initialized",
  "DEBUG - 2011-01-01 00:01:01 --> Database Driver Class Initialized",
  "DEBUG - 2011-01-01 00:01:01 --> Database Driver Class Initialized",
  "DEBUG - 2011-01-01 00:01:01 --> Session Class Initialized",
  "DEBUG - 2011-01-01 00:01:01 --> Session Class Initialized",
  "DEBUG - 2011-01-01 00:01:01 --> Encrypt Class Initialized",
  "DEBUG - 2011-01-01 00:01:01 --> Encrypt Class Initialized",
  "DEBUG - 2011-01-01 00:01:01 --> Session routines successfully run",
  "DEBUG - 2011-01-01 00:01:01 --> Session routines successfully run",
  "DEBUG - 2011-01-01 00:01:01 --> Controller Class Initialized",
  "DEBUG - 2011-01-01 00:01:01 --> Controller Class Initialized",
  "INFO  - 2011-01-01 00:01:01 --> Total execution time: 0.0404",
  "INFO  - 2011-01-01 00:01:01 --> New User: meowcats",
  "INFO  - 2011-01-01 00:01:01 --> Database cleanup, execution time: 1.05s",
  "INFO  - 2011-01-01 00:01:01 --> New upload by lollipop87, Disk 11% usage",
  "WARN  - 2011-01-01 00:01:01 --> Access denied to admin section by logged in user: 'nighthawk', IP 72.64.62.104",
  "WARN  - 2011-01-01 00:01:01 --> Access denied to admin section by logged in user: 'nighthawk', IP 72.64.62.104",
  "WARN  - 2011-01-01 00:01:01 --> Access denied to admin section by logged in user: 'nighthawk', IP 72.64.62.104",
  "ERROR - 2011-01-01 00:01:01 --> Could not connect to Redis!",
  "ERROR - 2011-01-01 00:01:01 --> Could not upload file to s3! /var/www/uploads/something.jpg",
	"FATAL - 2011-01-01 00:00:01 --> Could not connect to database!",
	"DEMO  - 2011-01-01 00:00:01 --> The database has no tables lol",
);


open handle, '>', 'log2.txt';

for(;;) {
  select((select(handle), $|=1)[0]);
  print $lines[rand @lines] . "\n";
  print handle $lines[rand @lines] . "\n";
	sleep 1;
}
